---
title: Een handleiding voor Unity
hero_image: images/banner.png
description: De basis van het gebruik van de Unity Editor
version: 4
listed: true
copyedit: true
last_tested: '2021-11-16'
steps:
  - 
    title: Unity-handleiding
  - 
    title: Overzicht van de verschillende Unity accounts
  - 
    title: Installeer Unity
  - 
    title: Install Visual Studio Code
  - 
    title: Nuttige bronnen
  - 
    title: Share projects
  - 
    title: Our Unity projects
