---
title: Un guide pour Unity
hero_image: images/banner.png
description: Les bases de l'utilisation de l'éditeur Unity
version: 4
listed: true
copyedit: true
last_tested: '2021-11-16'
steps:
  - 
    title: Guide de Unity
  - 
    title: Aperçu des comptes
  - 
    title: Installer Unity
  - 
    title: Install Visual Studio Code
  - 
    title: Ressources utiles
  - 
    title: Share projects
  - 
    title: Our Unity projects
